apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web-server-rc
  name: web-server-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: web-server-rc
    spec:
      containers:
      - image: quay.io/openshifttest/nginx-alpine@sha256:5d3f3372288b8a93fc9fc7747925df2328c24db41e4b4226126c3af293c5ad88
        name: nginx
        ports:
        - containerPort: 8080
        - containerPort: 8443
      hostNetwork: true
